steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sleep-calendar-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sleep-calendar-api:latest'
      - '.'
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/sleep-calendar-api'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sleep-calendar-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sleep-calendar-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GOOGLE_CALENDAR_CREDENTIALS=${_GOOGLE_CALENDAR_CREDENTIALS}'

images:
  - 'gcr.io/$PROJECT_ID/sleep-calendar-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sleep-calendar-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GOOGLE_CALENDAR_CREDENTIALS: ''
