#!/bin/bash
# Alternative: Use Mac Shortcuts app (similar to iOS)

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "📱 Mac Shortcuts Alternative"
echo "================================================"
echo ""
echo "You can also use the Shortcuts app on Mac:"
echo ""
echo "1. Open Shortcuts app"
echo "2. Create new shortcut"
echo "3. Add 'Run Shell Script' action:"
echo "   $SCRIPT_DIR/auto_export_mac.sh"
echo "4. Save as 'Export Sleep Data'"
echo ""
echo "5. In Shortcuts → Settings:"
echo "   - Allow running scripts"
echo ""
echo "6. Create Automation:"
echo "   - Open Shortcuts → Automation tab"
echo "   - Create Personal Automation"
echo "   - Time of Day → 4:00 AM → Daily"
echo "   - Run Shortcut → 'Export Sleep Data'"
echo ""
echo "This is more visual and Apple-native!"
echo ""
echo "Or use launchd (recommended): ./setup_cron.sh"
